name: flutter_smart_dialog
description:
  An elegant Flutter Dialog solution,
  Easily implement Toast, Loading and custom Dialog,
  Make the use of the dialog easier!
version: 3.0.1
author: 小呆呆666
homepage: https://github.com/fluttercandies/flutter_smart_dialog
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.22.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
